### ISSUE TITLE
Expressions

### ISSUE THREAD

**Issue by tomaszcekalo** [tomaszcekalo/StaticProgramAnalyzer#13]
wyrażenia przypisania prawdopodobnie potrzebują swojego drzewka. Do przedyskutowania

**Comment by tomaszcekalo** [comment]
a przynajmniej wyłuskania z nich jakich zmiennych używają

**Comment by LukaszGasowski** [comment]
Wersja 727844e działa z każdym możliwym działaniem, które może się pojawić w iteracji I, II i III. Obsługuje nawiasy.
Używane zmienne są przechowywane w postaci HashSet<String> w AssigmentToken.UsesVariables.
Używane stałe są przechowywane w postaci HashSet<String> w AssigmentToken.UsesConstans.
Do AssigmentToken zostały dodane funkcje do porównywania z innymi AssigmentTokenami (Sprawdzanie patternów w zapytaniach SQL właśnie na tym polega) :
ContainsTree oraz EqualsTree, odpowiednio pattern (_, _search_string_) oraz pattern (_, search_string). 
Lewa część paternu powinna być porównywana poza AssigmentTokenem lub przy użyciu innych funkcji.

Do zastanowienia, 
- czy procedure powinno również zawierać używane zmienne i stałe celem szybszemu odpytywaniu zapytań.
- globalne wyłączenie obliczania testowych wartości (są tylko potrzebne podczas testów)
